// Persona 1 


CREATE TABLE Socios (
    socio_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_socios PRIMARY KEY,
    cedula VARCHAR2(20) CONSTRAINT unq_socios_cedula UNIQUE NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    fecha_nacimiento DATE,
    direccion VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(50),
    preferencias CLOB,
    configuracion_privacidad VARCHAR2(50)
);

CREATE TABLE CategoriasMembresia (
    categoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_categorias PRIMARY KEY,
    nombre_categoria VARCHAR2(50) NOT NULL,
    descripcion CLOB,
    lista_privilegios CLOB,
    lista_beneficios CLOB
);

// Persona 2 

CREATE TABLE UsuariosSistema (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_usuarios PRIMARY KEY,
    nombre_usuario VARCHAR2(50) CONSTRAINT unq_usuarios_nombre_usuario UNIQUE NOT NULL,
    hash_password VARCHAR2(255) NOT NULL,
    rol_usuario VARCHAR2(20) CHECK (rol_usuario IN ('administrador','entrenador','socio')) NOT NULL,
    estado_usuario VARCHAR2(20) DEFAULT 'activo' CHECK (estado_usuario IN ('activo','inactivo')),
    socio_id NUMBER CONSTRAINT unq_usuarios_socio UNIQUE,
    CONSTRAINT fk_usuarios_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

CREATE TABLE Membresias (
    membresia_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_membresias PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    categoria_id NUMBER NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    estado_membresia VARCHAR2(20) DEFAULT 'activa' CHECK (estado_membresia IN ('activa','inactiva')),
    tarifa NUMBER(10,2),
    CONSTRAINT fk_membresias_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id),
    CONSTRAINT fk_membresias_categoria FOREIGN KEY (categoria_id) REFERENCES CategoriasMembresia(categoria_id)
);

// Persona 3 

CREATE TABLE Pagos (
    pago_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_pagos PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    fecha_pago DATE,
    monto_pago NUMBER(10,2),
    metodo_pago VARCHAR2(50),
    estado_pago VARCHAR2(20) DEFAULT 'pendiente' CHECK (estado_pago IN ('pendiente','completado','cancelado')),
    CONSTRAINT fk_pagos_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

CREATE TABLE Facturas (
    factura_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_facturas PRIMARY KEY,
    pago_id NUMBER NOT NULL,
    fecha_factura DATE,
    monto_factura NUMBER(10,2),
    estado_factura VARCHAR2(20) DEFAULT 'emitida' CHECK (estado_factura IN ('emitida','cancelada')),
    pasarela_pago VARCHAR2(50),
    CONSTRAINT fk_facturas_pago FOREIGN KEY (pago_id) REFERENCES Pagos(pago_id)
);

CREATE TABLE ProgramaFidelizacion (
    programa_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_programa PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    fecha_registro TIMESTAMP,
    puntos_acumulados NUMBER DEFAULT 0,
    recompensa_programa VARCHAR2(100),
    descripcion_programa CLOB,
    CONSTRAINT fk_programa_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

// Persona 4 

CREATE TABLE Eventos (
    evento_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_eventos PRIMARY KEY,
    nombre_evento VARCHAR2(100) NOT NULL,
    tipo_evento VARCHAR2(20) CHECK (tipo_evento IN ('social','cultural','deportivo','comunitario')) NOT NULL,
    fecha_evento TIMESTAMP,
    lugar_evento VARCHAR2(100),
    costo_evento NUMBER(10,2),
    descripcion_evento CLOB
);

CREATE TABLE Inscripciones (
    inscripcion_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_inscripciones PRIMARY KEY,
    evento_id NUMBER NOT NULL,
    socio_id NUMBER NOT NULL,
    fecha_inscripcion TIMESTAMP,
    estado_inscripcion VARCHAR2(20) DEFAULT 'pendiente' CHECK (estado_inscripcion IN ('confirmado','pendiente','cancelado')),
    pago_id NUMBER,
    CONSTRAINT fk_inscripciones_evento FOREIGN KEY (evento_id) REFERENCES Eventos(evento_id),
    CONSTRAINT fk_inscripciones_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id),
    CONSTRAINT fk_inscripciones_pago FOREIGN KEY (pago_id) REFERENCES Pagos(pago_id)
);

CREATE TABLE EncuestasSatisfaccion (
    encuesta_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_encuestas PRIMARY KEY,
    evento_id NUMBER NOT NULL,
    socio_id NUMBER NOT NULL,
    calificacion NUMBER CHECK (calificacion BETWEEN 1 AND 5),
    comentarios_encuesta CLOB,
    CONSTRAINT fk_encuestas_evento FOREIGN KEY (evento_id) REFERENCES Eventos(evento_id),
    CONSTRAINT fk_encuestas_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

CREATE TABLE Mensajes (
    mensaje_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_mensajes PRIMARY KEY,
    remitente_id NUMBER NOT NULL,
    destinatario_id NUMBER NOT NULL,
    fecha_envio TIMESTAMP,
    contenido_mensaje CLOB,
    tipo_mensaje VARCHAR2(20) DEFAULT 'directo' CHECK (tipo_mensaje IN ('directo','anuncio')),
    CONSTRAINT fk_mensajes_remitente FOREIGN KEY (remitente_id) REFERENCES UsuariosSistema(usuario_id),
    CONSTRAINT fk_mensajes_destinatario FOREIGN KEY (destinatario_id) REFERENCES UsuariosSistema(usuario_id)
);

CREATE TABLE Anuncios (
    anuncio_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_anuncios PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    titulo_anuncio VARCHAR2(100),
    contenido_anuncio CLOB,
    fecha_publicacion TIMESTAMP,
    tipo_anuncio VARCHAR2(20) CHECK (tipo_anuncio IN ('noticia','logro','evento')),
    CONSTRAINT fk_anuncios_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

CREATE TABLE Foros (
    foro_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_foros PRIMARY KEY,
    tema_foro VARCHAR2(100),
    fecha_creacion TIMESTAMP
);

CREATE TABLE ComentariosForo (
    comentario_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_comentarios PRIMARY KEY,
    foro_id NUMBER NOT NULL,
    socio_id NUMBER NOT NULL,
    contenido_comentario CLOB,
    fecha_comentario TIMESTAMP,
    CONSTRAINT fk_comentarios_foro FOREIGN KEY (foro_id) REFERENCES Foros(foro_id),
    CONSTRAINT fk_comentarios_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id)
);

// Persona 5 

CREATE TABLE Instalaciones (
    instalacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_instalaciones PRIMARY KEY,
    nombre_instalacion VARCHAR2(50) NOT NULL,
    tipo_instalacion VARCHAR2(30) CHECK (tipo_instalacion IN ('cancha','piscina','salon','area_recreativa')) NOT NULL,
    disponibilidad NUMBER(1) DEFAULT 1 CHECK (disponibilidad IN (0,1)),
    tarifa_instalacion NUMBER(10,2),
    estado_instalacion VARCHAR2(20) DEFAULT 'disponible' CHECK (estado_instalacion IN ('disponible','mantenimiento','cerrado'))
);

CREATE TABLE Reservas (
    reserva_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_reservas PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    instalacion_id NUMBER NOT NULL,
    fecha_reserva DATE,
    hora_inicio TIMESTAMP,
    hora_fin TIMESTAMP,
    estado_reserva VARCHAR2(20) DEFAULT 'pendiente' CHECK (estado_reserva IN ('confirmada','pendiente','cancelada')),
    recurrente NUMBER(1) DEFAULT 0 CHECK (recurrente IN (0,1)),
    CONSTRAINT fk_reservas_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id),
    CONSTRAINT fk_reservas_instalacion FOREIGN KEY (instalacion_id) REFERENCES Instalaciones(instalacion_id)
);

CREATE TABLE HistorialSocio (
    historial_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_historial PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    evento_id NUMBER,
    reserva_id NUMBER,
    pago_id NUMBER,
    fecha_registro TIMESTAMP,
    detalle_historial CLOB,
    CONSTRAINT fk_historial_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id),
    CONSTRAINT fk_historial_evento FOREIGN KEY (evento_id) REFERENCES Eventos(evento_id),
    CONSTRAINT fk_historial_reserva FOREIGN KEY (reserva_id) REFERENCES Reservas(reserva_id),
    CONSTRAINT fk_historial_pago FOREIGN KEY (pago_id) REFERENCES Pagos(pago_id)
);

CREATE TABLE Auditorias (
    auditoria_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_auditorias PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    fecha_auditoria TIMESTAMP,
    accion_auditoria VARCHAR2(100),
    entidad_afectada VARCHAR2(50),
    detalle_auditoria CLOB,
    CONSTRAINT fk_auditorias_usuario FOREIGN KEY (usuario_id) REFERENCES UsuariosSistema(usuario_id)
);

CREATE TABLE Respaldos (
    respaldo_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_respaldos PRIMARY KEY,
    fecha_respaldo TIMESTAMP,
    ubicacion_respaldo VARCHAR2(100),
    tipo_respaldo VARCHAR2(20) CHECK (tipo_respaldo IN ('completo','incremental')),
    estado_respaldo VARCHAR2(20) DEFAULT 'exitoso' CHECK (estado_respaldo IN ('exitoso','fallido')),
    usuario_id NUMBER,
    CONSTRAINT fk_respaldos_usuario FOREIGN KEY (usuario_id) REFERENCES UsuariosSistema(usuario_id)
);

CREATE TABLE PlataformasExternas (
    plataforma_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_plataformas PRIMARY KEY,
    nombre_plataforma VARCHAR2(50) NOT NULL,
    tipo_plataforma VARCHAR2(20) CHECK (tipo_plataforma IN ('red_social','contable','calendario')) NOT NULL
   
);

CREATE TABLE Integraciones (
    integracion_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_integraciones PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    plataforma_id NUMBER NOT NULL,
    modulo_origen VARCHAR2(30) CHECK (modulo_origen IN ('Evento','Pago','Comunicacion')) NOT NULL,
    fecha_integracion TIMESTAMP,
    estado_integracion VARCHAR2(20) DEFAULT 'activa' CHECK (estado_integracion IN ('activa','inactiva')),
    descripcion_integracion CLOB,
    CONSTRAINT fk_integraciones_usuario FOREIGN KEY (usuario_id) REFERENCES UsuariosSistema(usuario_id),
    CONSTRAINT fk_integraciones_plataforma FOREIGN KEY (plataforma_id) REFERENCES PlataformasExternas(plataforma_id)
);

CREATE TABLE Mantenimientos (
    mantenimiento_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_mantenimientos PRIMARY KEY,
    instalacion_id NUMBER NOT NULL,
    tipo_mantenimiento VARCHAR2(20) CHECK (tipo_mantenimiento IN ('preventivo','correctivo')) NOT NULL,
    fecha_mantenimiento DATE,
    descripcion_mantenimiento CLOB,
    CONSTRAINT fk_mantenimientos_instalacion FOREIGN KEY (instalacion_id) REFERENCES Instalaciones(instalacion_id)
);

CREATE TABLE EvaluacionesInstalacion (
    evaluacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_evaluaciones PRIMARY KEY,
    socio_id NUMBER NOT NULL,
    instalacion_id NUMBER NOT NULL,
    calificacion NUMBER CHECK (calificacion BETWEEN 1 AND 5),
    comentarios_evaluacion CLOB,
    CONSTRAINT fk_evaluaciones_socio FOREIGN KEY (socio_id) REFERENCES Socios(socio_id),
    CONSTRAINT fk_evaluaciones_instalacion FOREIGN KEY (instalacion_id) REFERENCES Instalaciones(instalacion_id)
);



